
import BeanClass.StudentBean;
import DatabaseManager.DatabseManager;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.imageio.stream.ImageOutputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;


public class StudentRegistrationFrame extends javax.swing.JFrame {

    public StudentRegistrationFrame() {
        
        initComponents();
        genderComboBox.addItem("Male");
        genderComboBox.addItem("Female");
        getStudent();
    }
 private void getStudent(){
	

	try{
	          Vector v=DatabseManager.getStudent();
                   stdList.setListData(v);
				
	}catch(Exception e){
		e.printStackTrace();
		javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
	}
}    
private void addStudent(){

     
    String name = nameTextField.getText();
    String fname=fNameTextField.getText();
    String caste=casteTextField.getText();
    String  rollNo = rollNoTextField.getText();
    String phoneNo=phoneNoTextField.getText();
    String gender=(String)genderComboBox.getSelectedItem();
    

    try{
               	int rows=DatabseManager.addStudent(name,fname,caste,rollNo,phoneNo,gender);
	if(rows>=1){
	        	javax.swing.JOptionPane.showMessageDialog(this,rows+" Records Inserted."); 
		clear();
		getStudent();				
	}
    }catch(Exception e){
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage()); 
    }

}   //end    
private void deleteStudent(){
        StudentBean bean = (StudentBean)stdList.getSelectedValue();
    if(bean==null)return;
    try{
           int rows = DatabseManager.deleteStudent(bean.getStdId());
           if(rows>=1){
           javax.swing.JOptionPane.showMessageDialog(this,rows+"Record Removed.");
           deleteImage();
           getStudent();
           clear();
           }
    }catch(Exception e){
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage()); 
    }

}
private void deleteImage()
{
    //give your directory path here
    String path = "F:\\7th Semester\\DIP\\Image Processing Project\\Pictures\\"+nameTextField+".jpg";
        File imageFile = new File(path);
        boolean b = imageFile.delete();
        System.out.println("Picture deleted "+b);
}

private void updateStudent(){
     StudentBean bean=(StudentBean)stdList.getSelectedValue();
     if(bean==null)return;
     
    String name = nameTextField.getText();
    String fname=fNameTextField.getText();
    String caste=casteTextField.getText();
    String  rollNo = rollNoTextField.getText();
    String phoneNo=phoneNoTextField.getText();
    String gender=(String)genderComboBox.getSelectedItem();
     try{
	int rows=DatabseManager.updateStudent(bean.getStdId(),name,fname,caste,rollNo,phoneNo,gender);
	if(rows>=1){
	    javax.swing.JOptionPane.showMessageDialog(this,rows+" Record Modified.");
            getStudent();
	    clear();
        	}
     }catch(Exception e){
         e.printStackTrace();
         javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
     } 
}
private ImageIcon getIcon(String name) throws IOException
{
    //give your directory path here
        String path = "F:\\7th Semester\\DIP\\Image Processing Project\\Pictures\\"+name;
        File imageFile = new File(path);
        BufferedImage inputImage=null;
        try{
         inputImage = ImageIO.read(imageFile);
        
        
        }catch(Exception e)
        {
            return null;
        }
        ImageIcon imageIcon = new ImageIcon(inputImage);
            return imageIcon;

}
private void clear(){
    phoneNoTextField.setText("");
    rollNoTextField.setText("");
    nameTextField.setText("");
    fNameTextField.setText("");
    casteTextField.setText("");
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        stLabel = new javax.swing.JLabel();
        backgroundPanel = new javax.swing.JPanel();
        stdDataPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        fNameLabel = new javax.swing.JLabel();
        fNameTextField = new javax.swing.JTextField();
        casteLabel = new javax.swing.JLabel();
        casteTextField = new javax.swing.JTextField();
        rollNoLabel = new javax.swing.JLabel();
        rollNoTextField = new javax.swing.JTextField();
        phoneNoTextField = new javax.swing.JTextField();
        rollNoLabel1 = new javax.swing.JLabel();
        rollNoLabel2 = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        stdIdLabel = new javax.swing.JLabel();
        stdIdTextField = new javax.swing.JTextField();
        picPanel = new javax.swing.JPanel();
        picLabel = new javax.swing.JLabel();
        listPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stdList = new javax.swing.JList();
        buttonsPanel = new javax.swing.JPanel();
        uploadPicButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1555, 855));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        titlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stLabel.setFont(new java.awt.Font("Wide Latin", 1, 25)); // NOI18N
        stLabel.setText("Welcome to Student Registration ");
        titlePanel.add(stLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 740, 70));

        getContentPane().add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1490, 90));

        backgroundPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stdDataPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        stdDataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        nameLabel.setText("Name");
        stdDataPanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 100, 40));

        nameTextField.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        stdDataPanel.add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 420, 40));

        fNameLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        fNameLabel.setText("F.Name");
        stdDataPanel.add(fNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 100, 40));

        fNameTextField.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        stdDataPanel.add(fNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 420, 40));

        casteLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        casteLabel.setText("Caste");
        stdDataPanel.add(casteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, 40));

        casteTextField.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        stdDataPanel.add(casteTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 420, 40));

        rollNoLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        rollNoLabel.setText("Roll No");
        stdDataPanel.add(rollNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 100, 40));

        rollNoTextField.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        stdDataPanel.add(rollNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 420, 40));

        phoneNoTextField.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        stdDataPanel.add(phoneNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 420, 40));

        rollNoLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        rollNoLabel1.setText("Phone No");
        stdDataPanel.add(rollNoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 100, 40));

        rollNoLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        rollNoLabel2.setText("Gender");
        stdDataPanel.add(rollNoLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 100, 40));

        genderComboBox.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        stdDataPanel.add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 200, 40));

        stdIdLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        stdIdLabel.setText("ID");
        stdDataPanel.add(stdIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, 40));

        stdIdTextField.setEditable(false);
        stdIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdIdTextFieldActionPerformed(evt);
            }
        });
        stdDataPanel.add(stdIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 190, 40));

        backgroundPanel.add(stdDataPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 650, 490));

        picPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        picPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        picLabel.setBackground(new java.awt.Color(102, 102, 102));
        picLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        picPanel.add(picLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 354, 472));

        backgroundPanel.add(picPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 370, 490));

        listPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        listPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stdList.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        stdList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                stdListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(stdList);
        stdList.getAccessibleContext().setAccessibleParent(stdList);

        listPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 470));

        backgroundPanel.add(listPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, 410, 490));

        buttonsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        buttonsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uploadPicButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        uploadPicButton.setText("Upload Picture");
        uploadPicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadPicButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(uploadPicButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 360, 80));

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 180, 80));

        addButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 180, 80));

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 190, 80));

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 30, 320, 80));

        backgroundPanel.add(buttonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 1450, 130));

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1490, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void uploadPicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadPicButtonActionPerformed
        JFileChooser fileChooser=new JFileChooser();
        fileChooser.showOpenDialog(null);
        File f=fileChooser.getSelectedFile();
        BufferedImage bImage = null;
        try{
            int scaledWidth=354;
            int scaledHeight=472;
            String path=f.getAbsolutePath();
            File imageFile = new File(path);
            BufferedImage inputImage = ImageIO.read(imageFile);
//            System.out.println(imageFile.getName());
            // creates output image
            
           BufferedImage outputImage = new BufferedImage(scaledWidth,
                scaledHeight, inputImage.getType());
            
        // scales the input image to the output image
        Graphics2D g2d = outputImage.createGraphics();
        g2d.drawImage(inputImage, 0, 0, scaledWidth, scaledHeight, null);
        g2d.dispose();
        
        ImageIcon imageIcon = new ImageIcon(outputImage);
        picLabel.setIcon(imageIcon);
        
        //give your directory path here
        String path1 = "F:\\7th Semester\\DIP\\Image Processing Project\\Pictures\\"+nameTextField.getText()+".jpg";
        ImageIO.write(outputImage, "jpg", new File(path1));
          
        }catch(Exception e){e.printStackTrace();}
        System.out.println("Images were written succesfully.");
    }//GEN-LAST:event_uploadPicButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addStudent();
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
       updateStudent();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        deleteStudent();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void stdIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdIdTextFieldActionPerformed

    private void stdListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_stdListValueChanged
  StudentBean bean=(StudentBean)stdList.getSelectedValue();
   if(bean==null)return;

        try {
                        
            stdIdTextField.setText( ""+bean.getStdId());
            nameTextField.setText( bean.getName());
            fNameTextField.setText( bean.getFname());
            casteTextField.setText( bean.getCaste());
            rollNoTextField.setText( bean.getRollNo());
            phoneNoTextField.setText( bean.getPhoneNo());
            genderComboBox.setSelectedItem( bean.getGender());
            ImageIcon icon=getIcon(bean.getName()+".jpg");
            if(icon==null)
            {
                picLabel.setText("Image not found");
            }
            else
            {
                picLabel.setIcon(icon);
            }
        } catch (Exception ex) {
            Logger.getLogger(StudentRegistrationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

       
  

    }//GEN-LAST:event_stdListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegistrationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JLabel casteLabel;
    private javax.swing.JTextField casteTextField;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel fNameLabel;
    private javax.swing.JTextField fNameTextField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField phoneNoTextField;
    private javax.swing.JLabel picLabel;
    private javax.swing.JPanel picPanel;
    private javax.swing.JLabel rollNoLabel;
    private javax.swing.JLabel rollNoLabel1;
    private javax.swing.JLabel rollNoLabel2;
    private javax.swing.JTextField rollNoTextField;
    private javax.swing.JLabel stLabel;
    private javax.swing.JPanel stdDataPanel;
    private javax.swing.JLabel stdIdLabel;
    private javax.swing.JTextField stdIdTextField;
    private javax.swing.JList stdList;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton uploadPicButton;
    // End of variables declaration//GEN-END:variables
}
